version: '3.8'

services:
  # Serviço da sua aplicação PHP
  web:
    build: .
    container_name: crud_php_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # Serviço do Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: crud_php_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: netflix
      MYSQL_USER: netflix_user
      MYSQL_PASSWORD: netflix_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Importa automaticamente o seu arquivo SQL ao iniciar o banco pela primeira vez
      - ./netflix.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  db_data: